package(default_visibility = ["//visibility:public"])

java_library(
    name = "tests",
    srcs = [
        "TestImportScrubber.java"
    ],
    deps = [
        "//src/main/java/org/pubref/util/importscrubber"
    ],
)
